var dataLayer = window.dataLayer = window.dataLayer || []; var $ integrazapSearch = document.querySelector.bind (document); var telForm = $ integrazapSearch ('. form-wapp .validate-form form'). telefone || ''; var emailForm = $ integrazapSearch ('. form-wapp .validate-form form'). email || ''; var nomeForm = $ integrazapSearch ('. form-wapp .validate-form form'). firstname || ''; var mensagemForm = $ integrazapSearch ('. form-wapp .validate-form form'). mensagem || ''; function showIntegraZAP (integrazapMsg) {$ integrazapSearch ("# wappBox"). style.right = "0" ; $ integrazapSearch ("# wappBox"). style.left = "0"; document.body.style.overflow = "escondido"; $ integrazapSearch (". integrazap-background"). style.display = "bloquear"; se (typeof integrazapMsg! == 'undefined') {mensagemForm.valor = integrazapMsg;}}
function hideIntegraZAP () {$ integrazapSearch ("# wappBox"). style.right = "- 500px"; $ integrazapSearch ("# wappBox"). style.left = "auto"; document.body.style.overflow = "" ; $ integrazapSearch (". integrazap-background"). style.display = "none";}
function get_browser_name () {if (window.innerWidth <992) {var gowapp = 'https: //api.whatsapp.com';} else {var gowapp = 'https: //web.whatsapp.com';}
if (navigator.userAgent.indexOf ("Firefox")! = - 1)
gowapp = 'https: //web.whatsapp.com'; return gowapp;}
função getCookie (cname) {if (document.cookie.indexOf (cname)! = - 1) {var name = cname + "="; var ca = document.cookie.split (';'); var formObject = {}; para (var i = 0; i <ca.length; i ++) {var c = ca [i]; enquanto (c.charAt (0) == '') {c = c.substring (1);}
if (c.indexOf (name) == 0) {formObject = JSON.parse (c.substring (name.length, c.length));}}
if (telForm! = '') telForm.value = atob (formObject.telefone); if (emailForm! = '') emailForm.value = atob (formObject.email); if (nomeForm! = '') nomeForm.value = atob (formObject.nome);}}
function setCookie (cname, cvalue, exdays) {var d = new Date (); d.setTime (d.getTime () + (exdays * 24 * 60 * 60 * 1000)); var expires = "expires =" + d .toUTCString (); document.cookie = cname + "=" + cvalue + ";" + expira + "; path = /";}
function returnToForm () {$ integrazapSearch ('. form-wapp div.hiddenBox'). remove (); $ integrazapSearch ('. form-wapp form'). classList.remove ('hiddenBox'); if (mensagemForm! = ' ') mensagemForm.value =' ';}
function showMessageEnviado (data, nome) {var contentResponse = '<div class = "hiddenBox"> <p class = "pResponseForm"> <strong> Mensagem Enviada </strong> <span class = "dataEnvio"> em' + data + ' </span> <br> <br> <span> <b> '+ nome +' </b> em alguns instantes responderemos sua mensagem </span> </p> <div class = "container-form-btn"> <button tabindex = "5" target = "_ blank" class = "wappSend box-form-btn col-xs-12 col-md-6 btn btn-green enviar sendWhasApp returnButton" title = "Enviar"> Voltar </button> </div> </div> '; $ integrazapSearch ('. form-wapp .integrazap-1-2-1-1 '). insertAdjacentHTML (' afterend ', contentResponse); $ integrazapSearch ('. form-wapp form ' )classList.add ('hiddenBox'); $ integrazapSearch ('. form-wapp div.hiddenBox'). classList.add ('showForm');}
getCookie ('_ wapp_integrazap'); if ($ integrazapSearch ('. form-wapp .validate-form form')! == null) {$ integrazapSearch ('. form-wapp .validate-form form #loadIntegrazap'). addEventListener ( 'click', function (event) {event.preventDefault (); var submitButton = $ integrazapSearch ('. integrazap .modal-wapp .form-wapp .container-form-btn .submit'); var spanSubmitButton = $ integrazapSearch (' .integrazap .modal-wapp .form-wapp .container-form-btn .submit span '); var svgSubmitButton = $ integrazapSearch ('. integrazap .modal-wapp .form-wapp .container-form-btn .submit svg ') ; var isValid = true; var inputs = document.querySelectorAll ('. validate-form .valida'); for (var i = 0; i <inputs.length; i ++) {var index = i; var element = inputs [ i]; var inputValue = element.value.trim (); if (inputValue == '') {isValid = false;var alertEmptyInput = $ integrazapSearch ('. form-wapp #respostaSendWapp'); alertEmptyInput.classList.remove ('alert-success'); alertEmptyInput.classList.add ('alert-danger'); alertEmptyInput.innerText = 'Por favor, informe seus dados '; element.parentNode.classList.add (' alert-validate '); element.addEventListener (' keypress ', function () {this.parentNode.classList.remove (' alert-validate ');}); } else {element.parentNode.classList.remove ('alert-validate');}}parentNode.classList.remove ('alert-validate');});} else {element.parentNode.classList.remove ('alert-validate');}}parentNode.classList.remove ('alert-validate');});} else {element.parentNode.classList.remove ('alert-validate');}}
| Integrazap ',' event_label ': window.location.href});}
if (response.codGoogleAdsEvento! = '') {gtag ('evento', 'conversão', {'send_to': response.codGoogleAdsEvento});}
if (typeof fbq == 'function') {fbq ('track', 'Lead', {content_name: 'Integrazap |' + window.location.href, value: 1,00, currency: 'BRL'});}
if (typeof RdIntegration == 'object') {var data_array = [{name: 'email', value: email}, {name: 'identificador', value: 'Integrazap'}, {name: 'token_rdstation', value: response.rdstation}, {nome: 'nome', valor: nome}, {nome: 'telefone', valor: telefone}, {nome: 'mensagem', valor: mensagem}, {nome: 'atendente', valor: response.nomeAtendente}, {nome: 'telefone_atendente', valor: response.telAtendente}]; RdIntegration.post (data_array);}
decodeURIComponent (response.mensagem); if (response.link_whatsapp! == '') {var link = get_browser_name (); var capturaPagina = response.capturaPagina; link + = encodeURI (decodeURIComponent (response.link_whatsapp)); link + = response.mensagem ; link + = (capturaPagina == 1)? '% 0A' + location.href: ''; if (window.innerWidth <992) {window.location.href = link;} else {window.open (link, '_ blank ');}}
spanSubmitButton.classList.remove ('spinnerIcon'); svgSubmitButton.style.display = 'inline-block'; submitButton.disabled = false; dataLayer.push ({'event': 'integrazap-send', 'eventCategory': janela. location.hostname + '| Integrazap', 'eventAction': 'Enviar mensagem para Whatsapp - Integrazap', 'eventLabel': window.location.href});}}; var path = (location.hash! = "")? location .hash: location.pathname; xhttp.open ("POST", "https://integrazap.com.br/gadget-v.2/whats_send.php", true); xhttp.setRequestHeader ('Content-type', 'application / x-www-form-urlencoded'); xhttp.send ('jsUs =' + JSON.stringify ({url_path: path, telefone: btoa (telefone), email: btoa (email), nome: btoa (encodeURIComponent (nome)), mensagem: btoa (encodeURIComponent (mensagem)), y: btoa (y)}));}}); var v_obj,v_fun; função máscara W (o, f) {v_obj = o
v_fun = f
setTimeout ("execmascara ()", 1);}
função execmascara () {v_obj.value = v_fun (v_obj.value)}
função mtel (v) {v = v.replace (/ \ D / g, ""); v = v.replace (/ ^ (\ d {2}) (\ d) / g, "($ 1) $ 2" ); v = v.replace (/ (\ d) (\ d {4}) $ /, "$ 1- $ 2"); return v;}
var telW = $ integrazapSearch ('. telefoneWhats'); telW.onkeyup = function () {mascaraW (this, mtel);}
telW.addEventListener ("focusout", function () {if (telW.value.length <14) {telW.value = '';}}); if (emailForm! = '') {emailForm.addEventListener ("focusout" , function () {if (! validateEmail (this.value)) {this.value = '';}}); function validateEmail (email) {var re = / ^ (([^ <> () [\] \ \.,;: \ s @ \ "] + (\. [^ <> () [\] \\.,;: \ s @ \"] +) *) | (\ ". + \")) @ ((\ [[0-9] {1,3} \. [0-9] {1,3} \. [0-9] {1,3} \. [0-9] {1,3 } \]) | (([a-zA-Z \ -0-9] + \.) + [a-zA-Z] {2,})) $ /; retornar re.teste (email);}} }
função debounce (func, esperar = 10, imediato = verdadeiro) {deixar tempo limite; retornar função () {deixar contexto = isso, args = argumentos; deixar mais tarde = função () {tempo limite = nulo; se (! imediato) func.aplicar (contexto, args);}; deixe callNow = imediato &&! tempo limite; clearTimeout (tempo limite); tempo limite = setTimeout (mais tarde, aguarde); if (callNow) func.apply (contexto, args);};}; deixe scrollPos = 0 ; const navBtnWapp = document.querySelector ('. integrazap-btn-show-wapp-stick'); if (navBtnWapp! == null) {function checkPosition () {let windowY = window.scrollY; if (windowY <scrollPos) { navBtnWapp.classList.add ('is-visible'); navBtnWapp.classList.remove ('is-hidden');} else {navBtnWapp.classList.add ('is-hidden'); navBtnWapp.classList.remove ('é -visível');}
scrollPos = windowY;}
window.addEventListener ('scroll', debounce (checkPosition));}